version: "3.9"
services:
  app:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - ./downloads:/usr/src/app/downloads
      - ./logs:/usr/src/app/logs
    ports:
      - "17945:17945"
